spring:
  application:
    name: ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: ledger_user
    password: ledger_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false


